---
title: "R Notebook"
author: "Hamza Rashid"
email : "bolddusk@gmail.com"
description : "This notebook is for learning"
output: html_notebook
---
# Section 9 - Functions
Functions are created using the function() directive and are stored as R Objects just like anything else. In particular, they are objects of class "function"
f <- (<function arguments>){ ## Do something }

Functions in R are "first class objects", which means that they can be treated like any other R object.
Importantly
 - Functions can be passed as arguments to other functions
 - Functions can be nested, so that you can define functions inside function. 
 - The return value of the function is the last expression in the function body to be evaluated.

Function Arguments
Functions have named arguments which potentially have default values.
 - The formal arguments are the arguments included in the function definition.
 - The formals functions returns the list of all the formal arguments of a function.
 - Not every function call in R makes use of all the formal arguments.
 - Functions arguments can be missing or might have default values.
 
 Argument Matching
 Function arguments can also be partially matched, which is useful for interactive work. The order of operations when given an argument.
  1- Check for exact match for a named argument
  2- Check for partial match.
  3- check for positional match.
  
```{r}
double <- function(a,b){
  a^2
}

double(5,5)

sum <- function(a=0,b=0){
  a+b
}
sum(5)
```

  
  
  
  
  
  
  